import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const cases = JSON.parse(await readFile(resolve(root, 'data/cases.json'), 'utf8'))
const grouped = Map.groupBy(cases, (item) => item.mode)

const sections = [...grouped.entries()].map(([mode, items]) => {
  const rows = items.map(
    (item) =>
      `| [${item.title}](${item.sourceUrl}) | ${item.duration}s · ${item.resolution} · ${item.aspectRatio} | ${item.tags.map((tag) => `\`${tag}\``).join(' ')} |`,
  )
  return `## ${mode}\n\n| 案例 | 输出 | 标签 |\n| --- | --- | --- |\n${rows.join('\n')}`
})

const catalog = `# MiniMax H3 Case Catalog\n\n> Generated from \`data/cases.json\`. Do not edit this file by hand.\n\n${sections.join('\n\n')}\n`
await writeFile(resolve(root, 'CATALOG.md'), catalog)
console.log(`Generated CATALOG.md with ${cases.length} public cases.`)
